name: CI

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .dockerignore
      - .github/workflows/docker.yml
  repository_dispatch:
    # this event is submited via github.com/bots-house/github-actions-upstream-watch
    types: upstream_commit

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo  
        uses: actions/checkout@v2

      - name: Checkout upstream repo 
        uses: actions/checkout@v2
        with:
          repository: tdlib/telegram-bot-api
          path: upstream
          submodules: recursive
          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Get Version
        run: |
          # get telegram bot api version
          # telegram_bot_api_version=$(cd upstream && git rev-parse --short HEAD)
          
          # get tdlib version 
          # tdlib_version=$(cd upstream/td && git rev-parse --short HEAD)
          
          # concat tdlib and telegram bot api version
          # version=$telegram_bot_api_version-$tdlib_version

          # store variable for future use
          # echo "version=$version" >> $GITHUB_ENV
          
          TG_SERVER_VERSION=$(cat upstream/CMakeLists.txt | grep TelegramBotApi | cut -d " " -f3)
          # echo "TG_SERVER_VERSION=${TG_SERVER_VERSION}" >> $GITHUB_ENV
          echo ::set-output name=latest_tag::${TG_SERVER_VERSION}
          
          echo "Parsed version: ${TG_SERVER_VERSION}"
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push telegram-bot-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/telegram-bot-api:latest, ${{ secrets.DOCKERHUB_USERNAME }}/telegram-bot-api:${{ steps.download.outputs.latest_tag }}
